### ISSUE TITLE
bug:手机端触摸样式有问题

### ISSUE THREAD

**Issue by tianyanqiu** [sinoui/ripple#3]

**Comment by liujinxing** [comment]
@tianyanqiu 这个问题的原因主要是出在使用 `useEffect` 的宿主组件本身，在组件上加上下面的样式即可解决问题：

```css
-webkit-tap-highlight-color: transparent;
```

参看[-webkit-tap-highlight-color](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color)
